import React from 'react';

const EFFECTIVE_DATE = 'April 24, 2026';
const COMPANY = 'ModernEndpoint.tech';
const CONTACT_EMAIL = 'support@modernendpoint.tech';
const PRODUCT = 'Privileged Identity Monitor';

export default function PrivacyPage() {
  return (
    <div
      style={{
        minHeight: '100vh',
        background: '#0C0C11',
        color: 'var(--text-primary, #e8e8f0)',
        fontFamily: 'var(--font-sans, system-ui, sans-serif)',
        padding: '0 16px 80px',
      }}
    >
      <div style={{ maxWidth: 720, margin: '0 auto', padding: '64px 0 40px' }}>
        <a
          href="/"
          style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 40, textDecoration: 'none', color: '#E8784A', fontSize: 13, fontWeight: 600 }}
        >
          ← Back
        </a>

        <h1 style={{ fontSize: 32, fontWeight: 800, marginBottom: 8 }}>Privacy Policy</h1>
        <p style={{ fontSize: 13, color: '#888', marginBottom: 48 }}>Effective date: {EFFECTIVE_DATE}</p>

        <Section title="1. Overview">
          <p>
            {COMPANY} operates {PRODUCT}. This policy explains what information we collect,
            how we use it, and how we protect it. We believe in minimal data collection and
            full transparency.
          </p>
        </Section>

        <Section title="2. What We Collect">
          <p><strong style={{ color: '#e8e8f0' }}>Account & session data</strong></p>
          <ul>
            <li>Your name and email address (from your Microsoft 365 account, via OAuth)</li>
            <li>Your Microsoft 365 tenant ID and tenant name</li>
            <li>Session token (stored in a secure HTTP-only cookie, expires in 24 hours)</li>
          </ul>

          <p style={{ marginTop: 16 }}><strong style={{ color: '#e8e8f0' }}>Security & alert data</strong></p>
          <ul>
            <li>Sign-in log summaries (IP, country, app, risk level) — fetched from Microsoft Graph and stored in <strong>your own Azure Table Storage</strong></li>
            <li>Alerts generated by our detection engine — stored in your Azure subscription</li>
            <li>Settings and configuration — stored in your Azure subscription</li>
          </ul>

          <p style={{ marginTop: 16 }}><strong style={{ color: '#e8e8f0' }}>Billing data</strong></p>
          <ul>
            <li>Your subscription status (active / free) and Gumroad subscription ID</li>
            <li>Payment processing is handled entirely by Gumroad — we never see or store your payment details</li>
          </ul>
        </Section>

        <Section title="3. What We Do NOT Collect">
          <ul>
            <li>We do not store your users' full sign-in logs — only aggregated anomaly data</li>
            <li>We do not read your emails, files, or Teams messages</li>
            <li>We do not sell or share your data with third parties</li>
            <li>We do not use your data to train AI models</li>
            <li>We do not collect device fingerprints or track you across sites</li>
          </ul>
        </Section>

        <Section title="4. Where Data Is Stored">
          <p>
            All tenant security data (alerts, sign-in summaries, settings) is stored in{' '}
            <strong>your Azure subscription</strong> via Azure Table Storage.
            {COMPANY} can only access this data using the credentials you provide.
            If you disconnect your account, your data remains in your own Azure subscription
            and is not deleted by us.
          </p>
          <p style={{ marginTop: 10 }}>
            Account metadata (tenant name, email, last seen) is stored in our Azure Table Storage
            instance in the EU region, used only to power the service dashboard.
          </p>
        </Section>

        <Section title="5. Cookies">
          <p>
            We use a single session cookie (<code style={{ color: '#E8784A', fontSize: 12 }}>connect.sid</code>) to
            keep you logged in. It is HTTP-only, secure, and expires after 24 hours. We do not use
            tracking cookies or third-party analytics.
          </p>
        </Section>

        <Section title="6. Microsoft Graph Permissions">
          <p>
            To operate, the Service requests read-only access to your Microsoft 365 sign-in logs
            and directory data, and write access only for the specific remediation actions you
            explicitly authorize (e.g., revoking a session). A full list of requested permissions
            is shown during the consent screen.
          </p>
        </Section>

        <Section title="7. Data Retention">
          <p>
            You control alert and settings data retention through your Azure subscription.
            If you delete your Azure Table Storage, all data is permanently removed.
            Account metadata in our systems is deleted within 30 days of account deletion request.
          </p>
        </Section>

        <Section title="8. Your Rights">
          <ul>
            <li><strong>Access:</strong> Request a copy of your account data at any time</li>
            <li><strong>Deletion:</strong> Request deletion of your account metadata</li>
            <li><strong>Portability:</strong> Your security data already lives in your Azure — you own it</li>
          </ul>
          <p style={{ marginTop: 10 }}>
            To exercise these rights, email{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: '#E8784A' }}>{CONTACT_EMAIL}</a>
          </p>
        </Section>

        <Section title="9. Security">
          <p>
            All data is transmitted over HTTPS. Sessions are encrypted. We follow security best
            practices including regular dependency updates and access controls.
          </p>
        </Section>

        <Section title="10. Changes">
          <p>
            We may update this policy from time to time. Material changes will be communicated
            by email or in-app notice. Continued use of the Service constitutes acceptance.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            Privacy questions or requests:{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: '#E8784A' }}>{CONTACT_EMAIL}</a>
          </p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: 16, fontWeight: 700, marginBottom: 10, color: '#E8784A' }}>{title}</h2>
      <div style={{ fontSize: 14, color: '#bbb', lineHeight: 1.75 }}>{children}</div>
    </section>
  );
}
